"""added image column to Product model

Revision ID: 39c1a37cff80
Revises: 6dd3e6a63e0e
Create Date: 2020-11-19 13:55:53.284203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c1a37cff80'
down_revision = '6dd3e6a63e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
