"""updated category to category_id in Product model

Revision ID: 6dd3e6a63e0e
Revises: 89d7b5a4ecbc
Create Date: 2020-11-19 10:08:17.121177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd3e6a63e0e'
down_revision = '89d7b5a4ecbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_category_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_category_fkey', 'product', 'category', ['category'], ['id'])
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
